apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: python-app
          image: gcr.io/imposing-ratio-319309/python-abdelrahman
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-service
